theme = "hugo-theme-casper"
baseURL = "./"
languageCode = "en-us"
title = "Samples of Thoughts"
publishDir = "public"
paginate = 5
disqusshortname = "corriebar-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
disable_mathjax = false
comments = true


[params]
  description = "about data, statistics  and everything in between"
  author = "Corrie"
  logo = ""
  cover = "images/tea_with_books.jpg"
  githubName = "corriebar"
  hideHUGOSupport = true
  twitterName = "corrieaar"
  hideSuggestions = true
  RSSlinks = true
  readingTime = true
  readingTimeText = "Estimated reading time:"