theme = "hugo-theme-casper"
baseURL = "https://samples-of-thoughts.com/"
languageCode = "en-us"
title = "Samples of Thoughts"
copyright = "&copy; Corrie Bartelheimer {year}"
publishDir = "public"
paginate = 5
disqusshortname = "corriebar-github-io"
googleAnalytics = "UA-140745376-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$", "\\.csv$", "\\.ipynb$"]
disable_mathjax = false
comments = true


[params]
  description = "about data, statistics  and everything in between"
  author = "Corrie"
  logo = ""
  cover = "images/tea_with_books.jpg"
  githubName = "corriebar"
  hideHUGOSupport = true
  twitterName = "corrieaar"
  hideSuggestions = true
  RSSlinks = true
  readingTime = true
  readingTimeText = "Estimated reading time:"
   # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true
  hostName = "https://samples-of-thoughts.com"
  
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "python", "yaml"]
    highlightjsTheme = "googlecode"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
    
[permalinks]
    post = "/:year/:slug/"
    
# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Talks"
url = "/talks"
weight = 3