theme = "hugo-theme-casper"
baseURL = "https://corriebar.github.io/"
languageCode = "en-us"
title = "Samples of Thoughts"
publishDir = "../corriebar.github.io"
paginate = 5
disqusshortname = "corriebar-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]



[params]
  description = "about machine learning, statistics  and bits related to data science"
  author = "Corrie"
  logo = ""
  cover = "images/tea_with_books.jpg"
  githubName = "corriebar"
  hideHUGOSupport = true
  twitterName = "corrieaar"
  #hideSuggestions = false
  RSSlinks = true
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"