theme = "hugo-theme-casper"
baseURL = "https://samples-of-thoughts.com/"
languageCode = "en-us"
title = "Samples of Thoughts"
publishDir = "public"
paginate = 5
disqusshortname = "corriebar-github-io"
googleAnalytics = "UA-140745376-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$", "\\.csv$"]
disable_mathjax = false
comments = true


[params]
  description = "about data, statistics  and everything in between"
  author = "Corrie"
  logo = ""
  cover = "images/tea_with_books.jpg"
  githubName = "corriebar"
  hideHUGOSupport = true
  twitterName = "corrieaar"
  hideSuggestions = true
  RSSlinks = true
  readingTime = false
  readingTimeText = "Estimated reading time:"
   # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false